string = input()

for i in string:
    if i.lower() == 'a': print('@', end='')
    elif i.lower() == 'b': print('8', end='')
    elif i.lower() == 'c': print('(', end='')
    elif i.lower() == 'd': print('|)', end='')
    elif i.lower() == 'e': print('3', end='')
    elif i.lower() == 'f': print('#', end='')
    elif i.lower() == 'g': print('6', end='')
    elif i.lower() == 'h': print('[-]', end='')
    elif i.lower() == 'i': print('|', end='')
    elif i.lower() == 'j': print('_|', end='')
    elif i.lower() == 'k': print('|<', end='')
    elif i.lower() == 'l': print('1', end='')
    elif i.lower() == 'm': print('[]\/[]', end='')
    elif i.lower() == 'n': print('[]\[]', end='')
    elif i.lower() == 'o': print('0', end='')
    elif i.lower() == 'p': print('|D', end='')
    elif i.lower() == 'q': print('(,)', end='')
    elif i.lower() == 'r': print('|Z', end='')
    elif i.lower() == 's': print('$', end='')
    elif i.lower() == 't': print('\'][\'', end='')
    elif i.lower() == 'u': print('|_|', end='')
    elif i.lower() == 'v': print('\/', end='')
    elif i.lower() == 'w': print('\/\/', end='')
    elif i.lower() == 'x': print('}{', end='')
    elif i.lower() == 'y': print('`/', end='')
    elif i.lower() == 'z': print('2', end='')
    else: print(i, end="")